server:
  nodeSelector:
    node.kubernetes.io/assignment: monitoring
  persistentVolume:
    storageClass: gp2
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - ""

alertmanager:
  nodeSelector:
    node.kubernetes.io/assignment: monitoring
  persistentVolume:
    storageClass: gp2

pushgateway:
  nodeSelector:
    node.kubernetes.io/assignment: monitoring