server:
  nodeSelector:
    node.kubernetes.io/assignment: monitoring
  persistentVolume:
    storageClass: gp2


alertmanager:
  nodeSelector:
    node.kubernetes.io/assignment: monitoring
  persistentVolume:
    storageClass: gp2

pushgateway:
  nodeSelector:
    node.kubernetes.io/assignment: monitoring