output "cluster_endpoint" {
  value = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value = module.eks.cluster_security_group_id
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value = module.eks.kubeconfig
}

output "region" {
  description = "AWS region"
  value = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value = var.cluster_name
}

output "ecr_registry" {
  value = data.aws_ecr_repository.ecr
}